### PR TITLE
346 - Add Orange small logo favicon to the documentation site

### PR DESCRIPTION
**Pull request by paulinea**

### CODE REVIEW

**Comment by julien-deramond** [comment]
@paulinea Can't we embed all of that directly in https://github.com/Orange-OpenSource/ods-jekyll-theme so that all projects can have it automatically? I'm thinking of modifying [the header](https://github.com/Orange-OpenSource/ods-jekyll-theme/blob/main/_includes/head.html), adding images in `assets/favicons`.
Can help if needed.

**Comment by paulinea** [comment]
@julien-deramond I think it will be better of course to factorize that in the Jekyll theme. Can I create a PR on this project to do so ? How can I test after ?

**Comment by julien-deramond** [comment]
Yep you can create a PR directly in this project. There's a procedure to test it locally. But in order to see if it works here, I'm afraid that we will need to merge it and then check here if it works. But I don't mind doing it like this.
In the Jekyll project, if not already there, please don't forget to create a NOTICE.txt file as well to mention the images with Orange property.

**Comment by paulinea** [comment]
Replaced by #370

**Pull request closed without merging**
